### ISSUE TITLE
tutorial to install it

### ISSUE THREAD

**Issue by ansharmuhammad** [ihh/graphgram#2]
I am very interested in this. can you tell me how to install it?

**Comment by ihh** [comment]
Hi Muhammad! This is available as an [npm module](https://www.npmjs.com/package/graphgram), so you can install it using `npm install graphgram` then run the code from the README. Unfortunately I do not have time to give more instructions as this is a side project for me, but you can find info on npm [here](https://nodesource.com/blog/an-absolute-beginners-guide-to-using-npm/) and JavaScript/node [here](https://www.tutorialspoint.com/nodejs/index.htm).
